name: python-ci

on:
  push: 
      branches: [main]
  pull_request: 
      branches: [main]
  
  # Habilitando o disparo manual
  workflow_dispatch: 

jobs:
  teste:

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        
        - name: Configurando o Flask
          run: |
            python -m pip install --upgrade pip
            pip install flask
        
        - name: Execução dos testes
          run:  python test_app.py
  
  build-imagem-docker:

    runs-on: ubuntu-latest
    needs: teste
    steps:     
    - uses: actions/checkout@v4

    - name: Construção da imagem Docker do backend
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: |
          matheus/flask-api:V${{github.run_number}}
          matheus/flask-api:latest
